"""TaskMixin — native tool task."""

import json
import logging
import uuid

from backend.agent.utils.contract import make_error_response, make_success_response, zero_usage
from backend.agent.utils.error_logger import log_error

logger = logging.getLogger(__name__)


class TaskMixin:
    async def task(self, agent_name: str, prompt: str) -> dict:
            """Delegate work to a sub-agent.

            Resolves the sub-agent's system prompt and permissions from its
            markdown definition, creates an integrated child session
            (``parent_id``), runs the agent loop inside that session, and
            returns the final answer wrapped in an XML block.

            The *prompt* argument is the **user task** the calling agent wants
            the sub-agent to perform (generated by the caller). The sub-agent's
            **system prompt** (its role / behaviour) is resolved here from its
            markdown.

            Args:
                agent_name: Name of the sub-agent to delegate to.
                prompt: Detailed task description for the sub-agent (user message).

            Returns:
                dict with ``{status, message, data, usage}``. ``data`` is the XML
                result block consumed by the parent agent as a tool result.
            """

            # 1. Resolve sub-agent data from its markdown definition
            # Check if loop.py already resolved permissions (cached on tools instance)
            # A parallel-loop snapshot (ContextVar) carries this call's resolved
            # config, so concurrent task() calls never read each other's cache.
            # The shared ``_task_config`` attribute is only used as a legacy
            # fallback for callers outside the agent loop. Lazy import: top-level
            # would be circular (loop_helpers -> instances -> agent -> tools).
            from backend.agent.utils.loop_helpers import _tool_call_ctx

            snapshot_cfg = _tool_call_ctx.get()
            resolved_cfg = (
                snapshot_cfg.get("task_config")
                if snapshot_cfg is not None and "task_config" in snapshot_cfg
                else None
            )
            cached = resolved_cfg if resolved_cfg is not None else getattr(self, "_task_config", None)
            if cached and cached.get("agent_name") == agent_name:
                # Reuse cached values — avoids re-reading agent .md
                tool_perms = cached["tool_permissions"]
                skill_perms = cached["skill_permissions"]
                parameters = cached["parameters"]
                parent_model = cached.get("parent_model")
                parent_provider = cached.get("parent_provider")
                # Clear cache for next delegation
                self._task_config = None
            else:
                # First-time resolution (called outside loop.py). Fall back to the
                # agent singleton's globally-resolved model/provider as the parent
                # reference for the sub-agent.
                from backend.instances import agent as _agent_singleton
                parent_model = getattr(_agent_singleton, "_resolved_model", None)
                parent_provider = getattr(_agent_singleton, "provider", None)

                tool_perms: dict = {}
                tp = get_tool_permissions(agent_name)
                if tp.get("status") == "success":
                    try:
                        tool_perms = json.loads(tp["data"])
                    except (json.JSONDecodeError, TypeError) as e:
                        log_error(str(e), source="tools.py:task(tool_perms)")
                        tool_perms = {}

                skill_perms: dict = {}
                sp = get_skill_permissions(agent_name)
                if sp.get("status") == "success":
                    try:
                        skill_perms = json.loads(sp["data"])
                    except (json.JSONDecodeError, TypeError) as e:
                        log_error(str(e), source="tools.py:task(skill_perms)")
                        skill_perms = {}

                # Resolve model parameters from sub-agent frontmatter
                params_result = get_agent_parameters(agent_name)
                parameters: dict = {}
                if params_result.get("status") == "success":
                    try:
                        parameters = json.loads(params_result.get("data", "{}"))
                    except (json.JSONDecodeError, TypeError) as e:
                        log_error(str(e), source="tools.py:task(parameters)")

            # 1b. Resolve the sub-agent's system prompt via the shared builder

            # (build_system_prompt handles Behavior from AGENT.md, MANDATORY and
            # Fecha for sub-agents too). The agent existence is checked first so
            # a missing agent returns a user-friendly error instead of falling
            # back to the router prompt. Errors never raise: they are reported
            # as a user-friendly message to the front.
            prompt_result = get_agent_prompt(agent_name)
            if prompt_result.get("status") != "success":
                return make_error_response(
                    message=f"No se encontró el agente '{agent_name}'. Revisá que exista en la carpeta de agentes.",
                    usage=zero_usage(),
                )

            try:
                from backend.agent.utils.loop_helpers import build_system_prompt

                system_prompt = build_system_prompt(agent_name)
                # print(f'Agente: {agent_name}\n\nPrompt:\n{system_prompt}')
            except Exception as exc:
                log_error(str(exc), source="tools.py:task(system_prompt)")
                return make_error_response(
                    message=f"No se pudo preparar el agente '{agent_name}'. Revisá su definición e intentá de nuevo.",
                    usage=zero_usage(),
                )

            # 2. Create an integrated child session (parent_id = current session)
            from backend.instances import agent, session_manager

            # print(f'\n\n\n{"#"*80}\nSystem prompt:\n\n{system_prompt}\n{"#"*80}\n\n\n')

            # A parallel-loop snapshot (ContextVar) takes precedence over the
            # shared attributes, so concurrent task() calls cannot overwrite
            # each other's parent session, depth, cancel event or event queue.
            # Callers outside the agent loop leave it unset and the legacy
            # shared attributes are used, exactly as before.
            snapshot = _tool_call_ctx.get()
            if snapshot is not None:
                parent_id = snapshot.get("parent_session_id", getattr(self, "_current_session_id", None))
                depth = snapshot.get("depth", getattr(self, "_current_depth", 0))
                stream_cancel_event = snapshot.get(
                    "stream_cancel_event", getattr(self, "_stream_cancel_event", None)
                )
                event_queue = snapshot.get(
                    "subagent_event_queue", getattr(self, "_subagent_event_queue", None)
                )
            else:
                parent_id = getattr(self, "_current_session_id", None)
                depth = getattr(self, "_current_depth", 0)
                stream_cancel_event = getattr(self, "_stream_cancel_event", None)
                event_queue = getattr(self, "_subagent_event_queue", None)

            child_id = (
                f"{parent_id}:{agent_name}:{uuid.uuid4().hex[:8]}"
                if parent_id
                else f"{agent_name}:{uuid.uuid4().hex[:8]}"
            )
            create_res = session_manager.create_session(child_id, parent_id=parent_id)
            if create_res.get("status") != "success":
                return make_error_response(
                    message=f"No se pudo crear la sub-sesión: {create_res.get('message')}",
                    usage=zero_usage(),
                )

            # 3. Run the sub-agent loop inside the child session
            from backend.agent.loop import AgentLoop


            loop = AgentLoop(
                agent=agent,
                session_manager=session_manager,
            )
            final_text = ""
            state = "completed"
            if event_queue is not None:
                logger.info("task() has event_queue for child=%s", child_id[:8])
            else:
                logger.info("task() NO event_queue for child=%s", child_id[:8])
            try:

                async for sse in loop.run(
                    session_id=child_id,
                    user_message=prompt,
                    system_prompt=system_prompt,
                    tool_permissions=tool_perms,
                    skill_permissions=skill_perms,
                    parameters=parameters,
                    agent_name=agent_name,
                    depth=depth + 1,
                    parent_id=parent_id,
                    parent_model=parent_model,
                    parent_provider=parent_provider,
                    stream_cancel_event=stream_cancel_event,
                ):
                    if sse.strip() == "data: [DONE]":
                        break
                    if sse.startswith("data: "):
                        try:
                            payload = json.loads(sse[len("data: "):].strip())
                        except (json.JSONDecodeError, ValueError) as e:
                            log_error(str(e), source="tools.py:task(sse_parse)")
                            continue

                        # Forward sub-agent event to parent's SSE stream in real-time
                        if event_queue is not None:
                            sub_event = {
                                "type": "subagent_event",
                                "content": {
                                    "child_session_id": child_id,
                                    "agent_name": agent_name,
                                    "event": payload,
                                },
                            }
                            await event_queue.put(sub_event)
                            if payload.get("type") in ("tool_call", "tool_result"):
                                logger.info(
                                    ">> queued event type=%s child=%s",
                                    payload.get("type"),
                                    child_id[:8],
                                )

                        if payload.get("type") == "chunk":
                            final_text += payload.get("content", "")
            except Exception as exc:
                logger.exception("Error en sub-agente '%s': %s", agent_name, exc)
                log_error(str(exc), source="tools.py:task")
                final_text = "Ocurrió un error al ejecutar el sub-agente."
                state = "error"

            # 4. Return the result wrapped in XML (consumed by the parent as tool result)

            xml = (
                f'<task id="{child_id}" state="{state}">'
                f"<task_result>{final_text}</task_result>"
                f"</task>"
            )

            return make_success_response(
                message=f"Tarea delegada a '{agent_name}'.",
                data=xml,
                usage=zero_usage(),
            )
